
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.virtual-host=/
rabbitmq.exchange=chat.exchange
rabbitmq.room-routing-prefix=room.
rabbitmq.channel-pool-size=20
rabbitmq.room-count=20