server.port=8081

rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.virtual-host=/
rabbitmq.exchange=chat.exchange
rabbitmq.room-routing-prefix=room.
rabbitmq.room-count=20
rabbitmq.prefetch-count=50
rabbitmq.consumer-threads=8

broadcaster.enabled=true
broadcaster.base-url=http://localhost:8080
broadcaster.timeout-ms=2000
