server.port=8081

rabbitmq.host=172.31.11.98
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.virtual-host=/
rabbitmq.exchange=chat.exchange
rabbitmq.room-routing-prefix=room.
rabbitmq.room-count=20
rabbitmq.prefetch-count=50
rabbitmq.consumer-threads=8

broadcaster.enabled=true
#broadcaster.base-url=http://localhost:8080
broadcaster.base-url=http://chatflow-alb-308077375.us-west-2.elb.amazonaws.com
broadcaster.timeout-ms=2000

#which db and library, use private ip
spring.datasource.url=jdbc:mysql://172.31.6.73:3306/chatflow?useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
spring.datasource.username=chatapp
spring.datasource.password=wehavetoeat
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#max 20 connection, min 5, overtime 3s
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=3000
